### ISSUE TITLE
implement readline shortcuts and command history

### ISSUE THREAD

**Issue by vvuk** [xoofx/kalk#15]
readline command line editing is the closest thing to a universal standard that exists.  would be great if kalk supported these as well, for command line editing, history, and search.  https://github.com/mono/LineEditor might be helpful?

**Comment by xoofx** [comment]
So kalk is implementing its own line editing experience (history, completion, navigation, word navigation, braces matching...) but maybe I'm missing something with readline. Do you have more precise example about what you are missing?

**Comment by xoofx** [comment]
I don't know also on which platform you are working, but there is currently an issue with keyboard shortcuts #4 on macOS

**Comment by vvuk** [comment]
Largely the shortcuts (I'm on Windows) -- this would be the core set: https://github.com/mono/LineEditor#shortcuts

**Comment by xoofx** [comment]
Right, ok, so some shortcuts are different in kalk like e.g `ctrl+left` move cursor to left word, `ctrl-backspace` delete previous "word",  or for selecting text `ctrl+shift+left`, similar to code editors on Windows (and for instance, I prefer myself something like that). Accessing the history is `up` and `down`. Tab is completion so same. 

But the core problem is that today these shortcuts are hardcoded and not configurable while they should. 
As kalk is supporting already user defined shortcuts within the editor, that should not be much trouble to bring them.

**Comment by vvuk** [comment]
That's fair -- and changeable bindings would help.  The readline ones are relatively "standard" which is why I bring them up.

**Comment by xoofx** [comment]
> That's fair -- and changeable bindings would help. The readline ones are relatively "standard" which is why I bring them up.

Yeah, that's good know. Never realized. e.g in the Windows terminal in a dos prompt, `ctrl+left` is going to the left word and `Alt-b` doesn't work. But kalk could have a readline compatibility mode for these shortcut if necessary.

**Comment by vvuk** [comment]
yeah, cmd/terminal was always the odd one out :)  PowerShell fixes it with PSReadline

**Comment by xoofx** [comment]
The version 0.2.0 is providing configurable shortcuts for line editor actions and is adding a few readline shortcuts (see [keyboard shortcuts](https://kalk.dev/doc/user/#keyboard-shortcuts))

It doesn't contain all the readline shortcuts and at least the basic ones.
