### ISSUE TITLE
Make number format functions to respect the size of its parameter

### ISSUE THREAD

**Issue by hypeartist** [xoofx/kalk#2]
So that, say, ```bin(long(5))``` would output ```00000000 00000101``` instead of int-like ```00000101``` as it currently does. Same could be applied to ```hex(v)``` function.

**Comment by xoofx** [comment]
So that's on purpose from the code, but I don't remember why I preferred it that way:

https://github.com/xoofx/kalk/blob/52adede0b08b0069d8b9fc5ece18f2263bee0d7f/src/Kalk.Core/Modules/MiscModule.cs#L1295-L1302

So yeah, I don't have strong arguments against matching the actual size. 😅

**Comment by xoofx** [comment]
Should be fixed by commit f93c517 and will be available in the upcoming `0.2.0` version
