### ISSUE TITLE
Ignore currency and thousand separators

### ISSUE THREAD

**Issue by danvk** [xoofx/kalk#27]
Not sure if this is compatible with the goals of this project, but I've always wanted a command line calculator that ignored currency symbols (e.g. `$`) and thousand separators (`,` in the US, `.` in many other countries).

So for example:

```
>>> $1,000.00 / 4
$250
```

**Comment by xoofx** [comment]
Agreed, it would be nice but it's not really possible as the language is already using $ for local variables, so that $1 can point to a valid variable...
