### ISSUE TITLE
Is it possible to compile using MonoDevelop?

### ISSUE THREAD

**Issue by gcarreno** [xoofx/kalk#29]
Hi Alexandre Mutel(@xoofx),

Is it possible to compile `kalk` under MonoDevelop?

If so, could you please provide some instructions on the `README.md` file?

Many thanks in advance!!

Cheers,
Gus

**Comment by xoofx** [comment]
Can't tell, I have never used MonoDevelop, it's also a bit outdated, don't even know if it supports properly recent version of .NET... so might be probably easier to use VS Code...

**Comment by gcarreno** [comment]
Hey Alexandre Mutel(@xoofx),

Well, I was asking about `MonoDevelop`, but more importantly I was asking of a way to compile under **Linux**.

So, I guess that underlying question is more: How could I compile your work under **Linux**?

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Alexandre Mutel(@xoofx),

Nevermind that last question. I now have egg on my face :)

Once I followed the link on the README.md file pointing to the .NET 5.0 SDK install, it all clicked :)

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Alexandre Mutel(@xoofx),

I've now installed the .NET 5.0 SDK and built `kalk` on my Ubuntu 21.04.

I've ran it and it runs with no apparent issue.

Many thanks for this wonderful piece of work :)

Cheers,
Gus
