### ISSUE TITLE
[linux/WSL] clipboard only works if powershell.exe and/or clip.exe is in path

### ISSUE THREAD

**Issue by cerebrate** [xoofx/kalk#35]
Which is to say, if the Windows path has been duplicated into WSL, and while that's the default, it's not a guarantee.

(I prefer to turn off path copying because my Linux path is long enough without cramming all of my Windows path, relevant or not, into it. It also generates WSL errors when path translation can't cope with network paths.)

Maybe it would be possible to invoke these with their full paths, based on %SystemRoot% or the location of the "/Windows" directory under /mnt/c or other drive letter?

**Comment by xoofx** [comment]
I'm using the library https://github.com/CopyText/TextCopy and it is indeed expected to have the path to `powershell.exe`. I don't want to hack around in kalk, while you can fix it more easily by adding at least a path to where powershell is located.

**Comment by cerebrate** [comment]
Makes sense. I'll go take it up with the library authors. Thanks.
