### ISSUE TITLE
Ctrl-D to exit (Linux and macOS)

### ISSUE THREAD

**Issue by waltertross** [xoofx/kalk#40]
Unix-derived operating systems like Linux and macOS use Ctrl-D (^D, EOT, end-of-transmission) as input terminator, with the typical behavior of closing a terminal shell when typed after a prompt. Also the Python CLI, that shares the prompt (`>>>`) with kalk, closes on Linux and macOS when Ctrl-D is typed right after the prompt (after writing `^D` where the cursor was). Kalk could use ^D on Linux and Mac just like it uses ^Z on Windows.

**Comment by xoofx** [comment]
Relatively related #24

**Comment by xoofx** [comment]
Because shortcut are registered in an embedded kalk file [here](https://github.com/xoofx/kalk/blob/master/src/Kalk.Core/core.kalk) I had to introduce a new object `env` in order to detect the OS. Version 0.11.0+ will include this fix.

**Comment by ishvedov** [comment]
Please make same shortcut for Windows too.
