### ISSUE TITLE
i^3 returns 0

### ISSUE THREAD

**Issue by basketshoe** [xoofx/kalk#44]
i<sup>3</sup> returns 0 while it should be -i
![image](https://github.com/xoofx/kalk/assets/54729294/db6fabb2-c4aa-4dfb-8fa1-ded9df84db79)

Using kalk 0.11.0

**Comment by xoofx** [comment]
Thanks, good catch, fixed by b38a84e9050029dd30aae69ea9f615c9bdc0c01d

**Comment by basketshoe** [comment]
Still returns wrong output, it's now **i** while it should be **-i**
![image](https://github.com/xoofx/kalk/assets/54729294/5e14c11f-e6ed-4caf-9b29-8d575d114dba)

**Comment by xoofx** [comment]
Indeed, I don't know what I was thinking when I made the fix. 🤦 
The calculation behind is correct, but it is the display that is incorrect.

**Comment by basketshoe** [comment]
all good now, thanks for the quick fixes 👌🏻
